### ISSUE TITLE
Height of the map

### ISSUE THREAD

**Issue by Lightz11** [maxpowa/extjs6-leaflet#1]
hey! I got a problem. I tried my own code and yours to show a leafletmap in an Ext 6.2.1 application.
And everytime the map and some container around it gets the height 0... Do you know about that Problem and how can I fix it ?

**Comment by maxpowa** [comment]
Because the map is a dynamic element, ExtJS cannot figure out sizing automatically for it - you need to use a parent container with some form of a 'fill' layout defined. Please provide a code example and I can point out what you could try.

**Comment by Lightz11** [comment]
I solved it! I just pointed out the first div wich has the height of 0. It has the class .x-map-container. In my CSS i just give it now the height of 100%  and it works fine!

**Comment by maxpowa** [comment]
That also works.
